version: '3'

services:
  pazardan.com.tr:
    container_name: pazardan.com.tr
    image: pazardan.com.tr
    build:
      context: .
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internal

networks:
  internal:
    driver: bridge
